### Notice 등록 요청
POST http://localhost:9999/api/notices
Content-Type: application/json

{
    "title":"JPA 연습용 제목",
    "writer":"JPA Jin",
    "content":"JPA 연습용 내용"
}

### Notice 삭제

DELETE http://localhost:9999/api/notices/5
# DELETE http://localhost:9999/api/notices?notice_id=6 (X)
Content-Type: application/json


### Notice 한 건 조회
GET http://localhost:9999/api/notices/1
Accept: application/json

### Notice 목록 조회
GET http://localhost:9999/api/notices
Accept: application/json

### Notice 한 건 수정
PUT http://localhost:9999/api/notices/1
Content-Type: application/json

{
    "title": "수정된 제목입니다",
    "writer": "Jin",
    "content": "내용을 요렇게 수정해봤어요."
}